# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import types


class ConfigurationNotification(lapidary.runtime.ModelBase):
    
    level: str
    
    message: str
    
    url: typing.Union[
            str,
            None,
        ]
    
    persist: typing.Union[
            bool,
            None,
        ] = None
    
    open_in_new_window: typing.Union[
            bool,
            None,
        ] = None
