# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing


class settings(lapidary.runtime.ModelBase):
    
    date_format: str
    
    time_format: str
    
    task_command_queue_limit: dict[
            str,
            pydantic.JsonValue,
        ]
