# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import gsmtasks.components.schemas.WorkerTrack.properties.properties.schema
import types


class WorkerTrack(lapidary.runtime.ModelBase):
    
    type: typing.Union[
            str,
            None,
        ] = None
    
    id: typing.Union[
            str,
            None,
        ] = None
    
    geometry: pydantic.JsonValue = None
    
    properties: typing.Union[
            gsmtasks.components.schemas.WorkerTrack.properties.properties.schema.properties,
            None,
        ] = None
