# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import types


class RenderResponse(lapidary.runtime.ModelBase):
    
    task: str
    
    sender: typing.Union[
            str,
            None,
        ] = None
    
    user: typing.Union[
            str,
            None,
        ] = None
    
    event: typing.Union[
            str,
            None,
        ] = None
    
    recipient: typing.Union[
            str,
            None,
        ] = None
    
    emails: typing.Union[
            list[typing.Annotated[
                    str,
                    annotated_types.MaxLen(254,),
                ],],
            None,
        ] = None
    
    phones: typing.Union[
            list[typing.Annotated[
                    str,
                    annotated_types.MaxLen(128,),
                ],],
            None,
        ] = None
    
    app: typing.Union[
            bool,
            None,
        ] = None
    
    message: typing.Union[
            str,
            None,
        ] = None
