# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import datetime
import gsmtasks.components.schemas.Location.schema
import types


class NestedAddress(lapidary.runtime.ModelBase):
    
    raw_address: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(250,),
            ],
            None,
        ] = None
    
    formatted_address: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(250,),
            ],
            None,
        ] = None
    
    location: typing.Union[
            gsmtasks.components.schemas.Location.schema.Location,
            None,
        ] = None
    
    google_place_id: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(250,),
            ],
            None,
        ] = None
    
    point_of_interest: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(100,),
            ],
            None,
        ] = None
    
    street: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(200,),
            ],
            None,
        ] = None
    
    geocoding_provider: typing.Union[
            str,
            None,
        ]
    
    house_number: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(100,),
            ],
            None,
        ] = None
    
    apartment_number: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(100,),
            ],
            None,
        ] = None
    
    city: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(100,),
            ],
            None,
        ] = None
    
    state: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(100,),
            ],
            None,
        ] = None
    
    postal_code: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(100,),
            ],
            None,
        ] = None
    
    country: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(100,),
            ],
            None,
        ] = None
    
    country_code: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(2,),
            ],
            None,
        ] = None
    
    geocoded_at: typing.Union[
            datetime.datetime,
            None,
        ]
    
    geocode_failed_at: typing.Union[
            datetime.datetime,
            None,
        ]
    
    failed_at: pydantic.JsonValue = None
