# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import datetime
import types
import uuid


class Metafield(lapidary.runtime.ModelBase):
    
    id: uuid.UUID
    
    url: str
    
    account: str
    
    ordering: typing.Union[
            typing.Annotated[
                int,
                annotated_types.Le(2147483647,),
                annotated_types.Ge(0,),
            ],
            None,
        ] = None
    
    namespace: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(20,),
                pydantic.Field(pattern=r'^[a-z0-9_]+$',),
            ],
            None,
        ] = None
    
    key: typing.Annotated[
            str,
            annotated_types.MaxLen(20,),
            pydantic.Field(pattern=r'^[a-z0-9_]+$',),
        ]
    
    field_name: str
    
    value_type: typing.Union[
            str,
            None,
        ] = None
    
    label: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(40,),
            ],
            None,
        ] = None
    
    choices: typing.Union[
            list[typing.Annotated[
                    str,
                    annotated_types.MaxLen(100,),
                ],],
            None,
        ] = None
    
    choices_url: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(2048,),
            ],
            None,
        ] = None
    
    is_editable: typing.Union[
            bool,
            None,
        ] = None
    
    is_editable_assignee: typing.Union[
            bool,
            None,
        ] = None
    
    is_required: typing.Union[
            bool,
            None,
        ] = None
    
    is_required_before_complete: typing.Union[
            bool,
            None,
        ] = None
    
    is_persistent: typing.Union[
            bool,
            None,
        ] = None
    
    is_cloned: typing.Union[
            bool,
            None,
        ] = None
    
    is_searchable: typing.Union[
            bool,
            None,
        ] = None
    
    show_in_list_view: typing.Union[
            bool,
            None,
        ] = None
    
    show_in_detail_view: typing.Union[
            bool,
            None,
        ] = None
    
    show_in_mobile_app: typing.Union[
            bool,
            None,
        ] = None
    
    show_in_form: typing.Union[
            bool,
            None,
        ] = None
    
    show_in_pod: typing.Union[
            bool,
            None,
        ] = None
    
    show_when_task_type_assignment: typing.Union[
            bool,
            None,
        ] = None
    
    show_when_task_type_pick_up: typing.Union[
            bool,
            None,
        ] = None
    
    show_when_task_type_drop_off: typing.Union[
            bool,
            None,
        ] = None
    
    created_at: datetime.datetime
    
    updated_at: datetime.datetime
