# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import gsmtasks.components.schemas.WorkerFeature.properties.geometry.schema
import gsmtasks.components.schemas.WorkerFeature.properties.properties.schema
import types
import uuid


class WorkerFeature(lapidary.runtime.ModelBase):
    
    type: typing.Union[
            str,
            None,
        ] = None
    
    id: typing.Union[
            None,
            uuid.UUID,
        ] = None
    
    geometry: typing.Union[
            gsmtasks.components.schemas.WorkerFeature.properties.geometry.schema.geometry,
            None,
        ] = None
    
    properties: typing.Union[
            gsmtasks.components.schemas.WorkerFeature.properties.properties.schema.properties,
            None,
        ] = None
