# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import datetime
import gsmtasks.components.schemas.Location.schema
import types
import uuid


class ContactAddressExport(lapidary.runtime.ModelBase):
    
    id: uuid.UUID
    
    external_id: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(100,),
            ],
            None,
        ] = None
    
    account__name: typing.Union[
            str,
            None,
        ] = None
    
    contact__name: typing.Union[
            str,
            None,
        ] = None
    
    contact__company: typing.Union[
            str,
            None,
        ] = None
    
    contact__phones: typing.Union[
            list[str,],
            None,
        ] = None
    
    contact__emails: typing.Union[
            list[str,],
            None,
        ] = None
    
    contact__notes: typing.Union[
            str,
            None,
        ] = None
    
    address__raw_address: typing.Union[
            str,
            None,
        ] = None
    
    address__formatted_address: typing.Union[
            str,
            None,
        ] = None
    
    address__location: gsmtasks.components.schemas.Location.schema.Location
    
    address__google_place_id: typing.Union[
            str,
            None,
        ] = None
    
    address__point_of_interest: typing.Union[
            str,
            None,
        ] = None
    
    address__street: typing.Union[
            str,
            None,
        ] = None
    
    address__house_number: typing.Union[
            str,
            None,
        ] = None
    
    address__apartment_number: typing.Union[
            str,
            None,
        ] = None
    
    address__city: typing.Union[
            str,
            None,
        ] = None
    
    address__state: typing.Union[
            str,
            None,
        ] = None
    
    address__postal_code: typing.Union[
            str,
            None,
        ] = None
    
    address__country: typing.Union[
            str,
            None,
        ] = None
    
    address__country_code: typing.Union[
            str,
            None,
        ] = None
    
    is_orderer: typing.Union[
            bool,
            None,
        ] = None
    
    is_receiver: typing.Union[
            bool,
            None,
        ] = None
    
    source: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(100,),
            ],
            None,
        ] = None
    
    created_at: datetime.datetime
    
    updated_at: datetime.datetime
