# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import datetime
import decimal
import gsmtasks.components.schemas.InvoiceItem.schema
import gsmtasks.components.schemas.PatchedInvoice.properties.account.schema
import types
import uuid


class PatchedInvoice(lapidary.runtime.ModelBase):
    
    id: typing.Union[
            None,
            uuid.UUID,
        ] = None
    
    url: typing.Union[
            str,
            None,
        ] = None
    
    account: typing.Union[
            gsmtasks.components.schemas.PatchedInvoice.properties.account.schema.account,
            None,
        ] = None
    
    billing_method: typing.Union[
            str,
            None,
        ] = None
    
    state: typing.Union[
            str,
            None,
        ] = None
    
    period: typing.Union[
            list[datetime.date,],
            None,
        ] = None
    
    total_no_vat: typing.Union[
            decimal.Decimal,
            None,
        ] = None
    
    total_vat: typing.Union[
            decimal.Decimal,
            None,
        ] = None
    
    total_with_vat: typing.Union[
            decimal.Decimal,
            None,
        ] = None
    
    currency: typing.Union[
            str,
            None,
        ] = None
    
    vat: typing.Union[
            bool,
            None,
        ] = None
    
    due_date: typing.Union[
            datetime.date,
            None,
        ] = None
    
    paid_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    items: typing.Union[
            list[gsmtasks.components.schemas.InvoiceItem.schema.InvoiceItem,],
            None,
        ] = None
    
    pricing: typing.Union[
            None,
            uuid.UUID,
        ] = None
    
    confirmed_by: typing.Union[
            str,
            None,
        ] = None
    
    confirmed_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    created_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    updated_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
