# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import datetime
import types
import uuid


class Webhook(lapidary.runtime.ModelBase):
    
    id: uuid.UUID
    
    url: str
    
    account: str
    
    name: typing.Annotated[
            str,
            annotated_types.MaxLen(100,),
        ]
    
    version: typing.Union[
            str,
            None,
        ] = None
    
    state: str
    
    headers: typing.Union[
            dict[
                str,
                pydantic.JsonValue,
            ],
            None,
        ] = None
    
    target: typing.Annotated[
            str,
            annotated_types.MaxLen(2048,),
        ]
    
    task_events: typing.Union[
            bool,
            None,
        ] = None
    
    document_events: typing.Union[
            bool,
            None,
        ] = None
    
    signature_events: typing.Union[
            bool,
            None,
        ] = None
    
    review_events: typing.Union[
            bool,
            None,
        ] = None
    
    notification_emails: typing.Union[
            list[typing.Annotated[
                    str,
                    annotated_types.MaxLen(254,),
                ],],
            None,
        ] = None
    
    fail_message: str
    
    shared_secret: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(40,),
            ],
            None,
        ] = None
    
    activated_at: typing.Union[
            datetime.datetime,
            None,
        ]
    
    failed_at: typing.Union[
            datetime.datetime,
            None,
        ]
    
    created_at: datetime.datetime
    
    updated_at: datetime.datetime
