# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import datetime
import types
import uuid


class PatchedTaskForm(lapidary.runtime.ModelBase):
    
    id: typing.Union[
            None,
            uuid.UUID,
        ] = None
    
    url: typing.Union[
            str,
            None,
        ] = None
    
    task: typing.Union[
            str,
            None,
        ] = None
    
    name: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(50,),
            ],
            None,
        ] = None
    
    link: typing.Union[
            str,
            None,
        ] = None
    
    edit_url: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(2048,),
            ],
            None,
        ] = None
    
    view_url: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(2048,),
            ],
            None,
        ] = None
    
    pdf_url: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(2048,),
            ],
            None,
        ] = None
    
    open_in: typing.Union[
            str,
            None,
        ] = None
    
    completed: typing.Union[
            bool,
            None,
        ] = None
    
    created_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    updated_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
