# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import gsmtasks.components.schemas.TaskEventTrack.schema
import types


class TaskEventTrackList(lapidary.runtime.ModelBase):
    
    type: typing.Union[
            str,
            None,
        ] = None
    
    features: typing.Union[
            list[gsmtasks.components.schemas.TaskEventTrack.schema.TaskEventTrack,],
            None,
        ] = None
