# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import datetime
import decimal
import types
import uuid


class BraintreeTransaction(lapidary.runtime.ModelBase):
    
    id: uuid.UUID
    
    url: str
    
    invoice: str
    
    customer: str
    
    type: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(6,),
            ],
            None,
        ] = None
    
    status: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(24,),
            ],
            None,
        ] = None
    
    amount: decimal.Decimal
    
    currency: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(3,),
            ],
            None,
        ] = None
    
    timestamp: typing.Union[
            datetime.datetime,
            None,
        ]
    
    response: typing.Union[
            str,
            None,
        ]
    
    created_at: datetime.datetime
    
    updated_at: datetime.datetime
