# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import gsmtasks.components.schemas.NestedAddress.schema
import types
import uuid


class Account(lapidary.runtime.ModelBase):
    
    id: uuid.UUID
    
    url: str
    
    name: typing.Annotated[
            str,
            annotated_types.MaxLen(100,),
        ]
    
    state: str
    
    type: typing.Union[
            str,
            None,
        ] = None
    
    slug: typing.Annotated[
            str,
            pydantic.Field(pattern=r'^[-a-zA-Z0-9_]+$',),
        ]
    
    owner: str
    
    email: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(254,),
            ],
            None,
        ] = None
    
    notification_emails: typing.Union[
            list[typing.Annotated[
                    str,
                    annotated_types.MaxLen(254,),
                ],],
            None,
        ] = None
    
    review_emails: typing.Union[
            list[typing.Annotated[
                    str,
                    annotated_types.MaxLen(254,),
                ],],
            None,
        ] = None
    
    review_emails_to_assignee: typing.Union[
            bool,
            None,
        ] = None
    
    website: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(200,),
            ],
            None,
        ] = None
    
    registry_code: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(20,),
            ],
            None,
        ] = None
    
    vatin: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(20,),
            ],
            None,
        ] = None
    
    language: typing.Union[
            str,
            None,
        ] = None
    
    timezone: typing.Union[
            str,
            None,
        ] = None
    
    country_code: typing.Union[
            str,
            None,
        ] = None
    
    address: typing.Union[
            gsmtasks.components.schemas.NestedAddress.schema.NestedAddress,
            None,
        ] = None
    
    custom_integration_url: str
    
    failed_reasons: typing.Union[
            list[typing.Annotated[
                    str,
                    annotated_types.MaxLen(200,),
                ],],
            None,
        ] = None
    
    route_default_state: typing.Union[
            str,
            None,
        ] = None
    
    distance_units: typing.Union[
            str,
            None,
        ] = None
    
    task_duration: typing.Union[
            int,
            str,
            None,
        ] = None
    
    task_expiry_duration_from_complete_after: typing.Union[
            dict[
                str,
                pydantic.JsonValue,
            ],
            None,
        ] = None
    
    task_expiry_duration_from_complete_before: typing.Union[
            dict[
                str,
                pydantic.JsonValue,
            ],
            None,
        ] = None
    
    task_expiry_state: typing.Union[
            str,
            None,
        ] = None
    
    assignee_proximity_radius: typing.Union[
            typing.Annotated[
                int,
                annotated_types.Le(2147483647,),
                annotated_types.Ge(0,),
            ],
            None,
        ] = None
    
    date_format: typing.Union[
            str,
            None,
        ] = None
    
    time_format: typing.Union[
            str,
            None,
        ] = None
    
    route_start_address: typing.Union[
            gsmtasks.components.schemas.NestedAddress.schema.NestedAddress,
            None,
        ] = None
    
    route_end_address: typing.Union[
            gsmtasks.components.schemas.NestedAddress.schema.NestedAddress,
            None,
        ] = None
    
    optimize_after_create: typing.Union[
            bool,
            None,
        ] = None
    
    optimization_objective: typing.Union[
            str,
            None,
        ] = None
    
    reference_autogenerate: typing.Union[
            bool,
            None,
        ] = None
    
    reference_offset: typing.Union[
            typing.Annotated[
                int,
                annotated_types.Le(2147483647,),
                annotated_types.Ge(-2147483648,),
            ],
            None,
        ] = None
    
    reference_prefix: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(50,),
            ],
            None,
        ] = None
    
    reference_length: typing.Union[
            typing.Annotated[
                int,
                annotated_types.Le(2147483647,),
                annotated_types.Ge(-2147483648,),
            ],
            None,
        ] = None
    
    feature_show_unassigned_to_workers: typing.Union[
            bool,
            None,
        ] = None
    
    feature_task_created_sound: typing.Union[
            bool,
            None,
        ] = None
    
    feature_change_task_account: typing.Union[
            bool,
            None,
        ] = None
    
    feature_show_tutorial: typing.Union[
            bool,
            None,
        ] = None
    
    feature_navigation_app_selection: typing.Union[
            bool,
            None,
        ] = None
    
    feature_navigation_use_address: typing.Union[
            bool,
            None,
        ] = None
    
    feature_task_accept: typing.Union[
            bool,
            None,
        ] = None
    
    feature_task_reject: typing.Union[
            bool,
            None,
        ] = None
    
    feature_app_task_search: typing.Union[
            bool,
            None,
        ] = None
    
    feature_address_autosuggest_provider: typing.Union[
            str,
            None,
        ] = None
    
    feature_geocoding_country_code: str
    
    feature_document_signing: typing.Union[
            bool,
            None,
        ] = None
    
    feature_tracker_reviews_allowed: typing.Union[
            bool,
            None,
        ] = None
    
    feature_tracker_url: str
    
    feature_route_folders: bool
    
    feature_route_auto_archive: bool
    
    feature_signature_required: typing.Union[
            bool,
            None,
        ] = None
    
    feature_signature_required_task_category: typing.Union[
            list[str,],
            None,
        ] = None
    
    feature_picture_required: typing.Union[
            bool,
            None,
        ] = None
    
    feature_picture_required_task_category: typing.Union[
            list[str,],
            None,
        ] = None
    
    auto_assign_orders: typing.Union[
            bool,
            None,
        ] = None
    
    auto_assign_max_tasks: typing.Union[
            typing.Annotated[
                int,
                annotated_types.Le(2147483647,),
                annotated_types.Ge(-2147483648,),
            ],
            None,
        ] = None
    
    auto_assign_max_distance: typing.Union[
            typing.Annotated[
                int,
                annotated_types.Le(2147483647,),
                annotated_types.Ge(-2147483648,),
            ],
            None,
        ] = None
    
    auto_assign_time_before: typing.Union[
            str,
            None,
        ] = None
    
    auto_assign_rotate: typing.Union[
            dict[
                str,
                pydantic.JsonValue,
            ],
            None,
        ] = None
    
    auto_assign_optimize: typing.Union[
            bool,
            None,
        ] = None
    
    dashboard_task_template: str
    
    calendar_task_template: str
    
    dashboard_worker_limit: int
    
    stripe_customer_id: typing.Union[
            str,
            None,
        ]
    
    stripe_payment_method_id: typing.Union[
            str,
            None,
        ]
    
    billing_method: str
    
    billing_name: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(100,),
            ],
            None,
        ] = None
    
    billing_company: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(100,),
            ],
            None,
        ] = None
    
    billing_address: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(200,),
            ],
            None,
        ] = None
    
    billing_country: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(100,),
            ],
            None,
        ] = None
    
    billing_email: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(254,),
            ],
            None,
        ] = None
    
    billing_phone: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(20,),
            ],
            None,
        ] = None
    
    billing_vatin: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(20,),
            ],
            None,
        ] = None
