# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import types


class geometry(lapidary.runtime.ModelBase):
    
    type: typing.Union[
            str,
            None,
        ] = None
    
    coordinates: typing.Union[
            list[float,],
            None,
        ] = None
