# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import datetime
import types


class WorkingState(lapidary.runtime.ModelBase):
    
    account_role: typing.Union[
            str,
            None,
        ] = None
    
    account: typing.Union[
            str,
            None,
        ] = None
    
    user: typing.Union[
            str,
            None,
        ] = None
    
    mode: typing.Union[
            str,
            None,
        ] = None
    
    timestamp: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    status: str
    
    created_at: datetime.datetime
