# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import datetime
import types
import uuid


class Document(lapidary.runtime.ModelBase):
    
    id: uuid.UUID
    
    url: str
    
    account: typing.Union[
            str,
            None,
        ] = None
    
    external_id: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(100,),
            ],
            None,
        ] = None
    
    order: typing.Union[
            str,
            None,
        ] = None
    
    task: typing.Union[
            str,
            None,
        ] = None
    
    recurrence: typing.Union[
            str,
            None,
        ] = None
    
    file_upload: typing.Union[
            str,
            None,
        ] = None
    
    file: str
    
    file_name: typing.Union[
            str,
            None,
        ]
    
    mimetype: typing.Union[
            str,
            None,
        ]
    
    thumbnail: typing.Union[
            str,
            None,
        ]
    
    description: typing.Union[
            str,
            None,
        ] = None
    
    s3_response_headers: typing.Union[
            dict[
                str,
                pydantic.JsonValue,
            ],
            None,
        ] = None
    
    created_by: str
    
    source: typing.Union[
            str,
            None,
        ] = None
    
    visible_to_worker: typing.Union[
            bool,
            None,
        ] = None
    
    visible_to_client: typing.Union[
            bool,
            None,
        ] = None
    
    created_at: datetime.datetime
    
    updated_at: datetime.datetime
