# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import datetime
import types
import uuid


class PatchedClientRole(lapidary.runtime.ModelBase):
    
    id: typing.Union[
            None,
            uuid.UUID,
        ] = None
    
    url: typing.Union[
            str,
            None,
        ] = None
    
    account: typing.Union[
            str,
            None,
        ] = None
    
    client: typing.Union[
            str,
            None,
        ] = None
    
    user: typing.Union[
            str,
            None,
        ] = None
    
    phone: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(128,),
            ],
            None,
        ] = None
    
    is_manager: typing.Union[
            bool,
            None,
        ] = None
    
    is_active: typing.Union[
            bool,
            None,
        ] = None
    
    created_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    updated_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
