# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import datetime
import gsmtasks.components.schemas.Location.schema
import types
import uuid


class TaskExport(lapidary.runtime.ModelBase):
    
    id: typing.Union[
            None,
            uuid.UUID,
        ] = None
    
    external_id: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(100,),
            ],
            None,
        ] = None
    
    category: typing.Union[
            str,
            None,
        ] = None
    
    description: typing.Union[
            str,
            None,
        ] = None
    
    reference: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(100,),
            ],
            None,
        ] = None
    
    complete_after: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    complete_before: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    scheduled_time: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    state: str
    
    position: typing.Union[
            typing.Annotated[
                float,
                annotated_types.Le(253402300799.0,),
                annotated_types.Ge(0.0,),
            ],
            None,
        ] = None
    
    priority: typing.Union[
            typing.Annotated[
                int,
                annotated_types.Le(2147483647,),
                annotated_types.Ge(-2147483648,),
            ],
            None,
        ] = None
    
    duration: typing.Union[
            dict[
                str,
                pydantic.JsonValue,
            ],
            None,
        ] = None
    
    is_full_load: typing.Union[
            bool,
            None,
        ] = None
    
    assignee_proximity: typing.Union[
            str,
            None,
        ] = None
    
    auto_assign: typing.Union[
            bool,
            None,
        ] = None
    
    issues: typing.Union[
            list[str,],
            None,
        ] = None
    
    size: typing.Union[
            list[typing.Annotated[
                    int,
                    annotated_types.Le(2147483647,),
                    annotated_types.Ge(-2147483648,),
                ],],
            None,
        ] = None
    
    completed_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    cancelled_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    created_at: datetime.datetime
    
    updated_at: datetime.datetime
    
    contact_address_external_id: typing.Union[
            str,
            None,
        ]
    
    account__name: str
    
    order__id: typing.Union[
            str,
            None,
        ] = None
    
    order__external_id: typing.Union[
            str,
            None,
        ] = None
    
    order__reference: typing.Union[
            str,
            None,
        ] = None
    
    order__auto_assign: typing.Union[
            str,
            None,
        ] = None
    
    order__created_by: typing.Union[
            str,
            None,
        ] = None
    
    order__created_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    order__orderer__name: typing.Union[
            str,
            None,
        ] = None
    
    order__orderer__company: typing.Union[
            str,
            None,
        ] = None
    
    order__orderer__emails: typing.Union[
            list[str,],
            None,
        ] = None
    
    order__orderer__phones: typing.Union[
            list[str,],
            None,
        ] = None
    
    order__orderer__notes: typing.Union[
            str,
            None,
        ] = None
    
    orderer__name: typing.Union[
            str,
            None,
        ] = None
    
    contact__name: typing.Union[
            str,
            None,
        ] = None
    
    contact__company: typing.Union[
            str,
            None,
        ] = None
    
    contact__emails: typing.Union[
            list[str,],
            None,
        ] = None
    
    contact__phones: typing.Union[
            list[str,],
            None,
        ] = None
    
    contact__notes: typing.Union[
            str,
            None,
        ] = None
    
    assignee__display_name: str
    
    assignee__email: typing.Union[
            str,
            None,
        ] = None
    
    assignee__phone: typing.Union[
            str,
            None,
        ] = None
    
    address__raw_address: typing.Union[
            str,
            None,
        ] = None
    
    address__formatted_address: typing.Union[
            str,
            None,
        ] = None
    
    address__location: gsmtasks.components.schemas.Location.schema.Location
    
    address__google_place_id: typing.Union[
            str,
            None,
        ] = None
    
    address__point_of_interest: typing.Union[
            str,
            None,
        ] = None
    
    address__street: typing.Union[
            str,
            None,
        ] = None
    
    address__house_number: typing.Union[
            str,
            None,
        ] = None
    
    address__apartment_number: typing.Union[
            str,
            None,
        ] = None
    
    address__city: typing.Union[
            str,
            None,
        ] = None
    
    address__state: typing.Union[
            str,
            None,
        ] = None
    
    address__postal_code: typing.Union[
            str,
            None,
        ] = None
    
    address__country: typing.Union[
            str,
            None,
        ] = None
    
    address__country_code: typing.Union[
            str,
            None,
        ] = None
    
    address__geocoded_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    address__geocode_failed_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    route__code: typing.Union[
            str,
            None,
        ] = None
    
    route__description: typing.Union[
            str,
            None,
        ] = None
    
    created_by__display_name: str
    
    created_by__email: typing.Union[
            str,
            None,
        ] = None
    
    created_by__phone: typing.Union[
            str,
            None,
        ] = None
    
    metadata__events_count: int
    
    metadata__documents_count: int
    
    metadata__signatures_count: int
    
    metadata__forms_count: int
    
    metadata__forms_completed_count: int
    
    metadata__task_event_notes_count: typing.Union[
            int,
            None,
        ] = None
    
    metadata__last_task_event_notes: typing.Union[
            str,
            None,
        ] = None
    
    metadata__unassigned_duration: dict[
            str,
            pydantic.JsonValue,
        ]
    
    metadata__assigned_duration: dict[
            str,
            pydantic.JsonValue,
        ]
    
    metadata__accepted_duration: dict[
            str,
            pydantic.JsonValue,
        ]
    
    metadata__transit_duration: dict[
            str,
            pydantic.JsonValue,
        ]
    
    metadata__active_duration: dict[
            str,
            pydantic.JsonValue,
        ]
    
    metadata__completed_duration: dict[
            str,
            pydantic.JsonValue,
        ]
    
    metadata__failed_duration: dict[
            str,
            pydantic.JsonValue,
        ]
    
    metadata__cancelled_duration: dict[
            str,
            pydantic.JsonValue,
        ]
    
    metadata__unassigned_distance: int
    
    metadata__assigned_distance: int
    
    metadata__accepted_distance: int
    
    metadata__transit_distance: int
    
    metadata__active_distance: int
    
    metadata__completed_distance: int
    
    metadata__failed_distance: int
    
    metadata__cancelled_distance: int
    
    metadata__last_unassigned_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    metadata__last_assigned_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    metadata__last_accepted_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    metadata__last_transit_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    metadata__last_active_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    metadata__last_completed_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    metadata__last_failed_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    metadata__last_cancelled_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
