# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import types


class properties(lapidary.runtime.ModelBase):
    
    model: typing.Union[
            str,
            None,
        ] = None
    
    task: typing.Union[
            str,
            None,
        ] = None
    
    formatted_address: typing.Union[
            str,
            None,
        ] = None
    
    category: typing.Union[
            str,
            None,
        ] = None
    
    state: typing.Union[
            str,
            None,
        ] = None
