# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import types


class ResponseMetadata(pydantic.BaseModel):
    
    link: typing.Annotated[
            typing.Union[
            list[str,],
            None,
        ],
            lapidary.runtime.Header(style=lapidary.runtime.SimpleMultimap,),
        ] = None
