# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import datetime
import types
import uuid


class PatchedClient(lapidary.runtime.ModelBase):
    
    id: typing.Union[
            None,
            uuid.UUID,
        ] = None
    
    url: typing.Union[
            str,
            None,
        ] = None
    
    account: typing.Union[
            str,
            None,
        ] = None
    
    name: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(200,),
            ],
            None,
        ] = None
    
    slug: typing.Union[
            typing.Annotated[
                str,
                pydantic.Field(pattern=r'^[-a-zA-Z0-9_]+$',),
            ],
            None,
        ] = None
    
    archived: typing.Union[
            bool,
            None,
        ] = None
    
    created_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    updated_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    contact_addresses: typing.Union[
            list[dict[
                    str,
                    pydantic.JsonValue,
                ],],
            None,
        ] = None
