# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import datetime
import types
import uuid


class PatchedSMS(lapidary.runtime.ModelBase):
    
    id: typing.Union[
            None,
            uuid.UUID,
        ] = None
    
    url: typing.Union[
            str,
            None,
        ] = None
    
    account: typing.Union[
            str,
            None,
        ] = None
    
    external_id: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(34,),
            ],
            None,
        ] = None
    
    state: typing.Union[
            str,
            None,
        ] = None
    
    notification: typing.Union[
            str,
            None,
        ] = None
    
    sender: typing.Union[
            str,
            None,
        ] = None
    
    alphanumeric_sender_id: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(20,),
            ],
            None,
        ] = None
    
    phone: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(128,),
            ],
            None,
        ] = None
    
    message: typing.Union[
            str,
            None,
        ] = None
    
    segments_count: typing.Union[
            typing.Annotated[
                int,
                annotated_types.Le(2147483647,),
                annotated_types.Ge(-2147483648,),
            ],
            None,
        ] = None
    
    error: typing.Union[
            str,
            None,
        ] = None
    
    sent_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    failed_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    received_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    created_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
