# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import datetime
import gsmtasks.components.schemas.Location.schema
import gsmtasks.components.schemas.NestedContact.schema
import types
import uuid


class Signature(lapidary.runtime.ModelBase):
    
    id: uuid.UUID
    
    url: str
    
    account: typing.Union[
            str,
            None,
        ] = None
    
    external_id: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(100,),
            ],
            None,
        ] = None
    
    task: str
    
    file_upload: str
    
    file: str
    
    file_name: str
    
    mimetype: typing.Union[
            str,
            None,
        ]
    
    thumbnail: str
    
    signer: gsmtasks.components.schemas.NestedContact.schema.NestedContact
    
    documents: typing.Union[
            list[str,],
            None,
        ] = None
    
    location: typing.Union[
            gsmtasks.components.schemas.Location.schema.Location,
            None,
        ] = None
    
    s3_response_headers: typing.Union[
            dict[
                str,
                pydantic.JsonValue,
            ],
            None,
        ] = None
    
    created_by: str
    
    source: typing.Union[
            str,
            None,
        ] = None
    
    created_at: datetime.datetime
    
    updated_at: datetime.datetime
