# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import datetime
import types
import uuid


class NotificationTemplate(lapidary.runtime.ModelBase):
    
    id: uuid.UUID
    
    url: str
    
    account: str
    
    name: typing.Annotated[
            str,
            annotated_types.MaxLen(100,),
        ]
    
    event: typing.Union[
            str,
            None,
        ] = None
    
    state: typing.Union[
            str,
            None,
        ] = None
    
    task_category: typing.Union[
            str,
            None,
        ] = None
    
    scheduled_time_added: typing.Union[
            bool,
            None,
        ] = None
    
    scheduled_time_change: typing.Union[
            bool,
            None,
        ] = None
    
    recipient: typing.Union[
            str,
            None,
        ] = None
    
    emails: typing.Union[
            list[typing.Annotated[
                    str,
                    annotated_types.MaxLen(254,),
                ],],
            None,
        ] = None
    
    phones: typing.Union[
            list[typing.Annotated[
                    str,
                    annotated_types.MaxLen(128,),
                ],],
            None,
        ] = None
    
    via_sms: typing.Union[
            bool,
            None,
        ] = None
    
    via_email: typing.Union[
            bool,
            None,
        ] = None
    
    via_app: typing.Union[
            bool,
            None,
        ] = None
    
    is_active: typing.Union[
            bool,
            None,
        ] = None
    
    message: str
    
    email_reply_to: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(254,),
            ],
            None,
        ] = None
    
    created_at: datetime.datetime
    
    updated_at: datetime.datetime
