# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import datetime
import types
import uuid


class Email(lapidary.runtime.ModelBase):
    
    id: uuid.UUID
    
    url: str
    
    account: str
    
    external_id: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(34,),
            ],
            None,
        ] = None
    
    state: str
    
    notification: str
    
    sender: str
    
    from_email: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(254,),
            ],
            None,
        ] = None
    
    reply_to_email: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(254,),
            ],
            None,
        ] = None
    
    to_emails: typing.Union[
            list[typing.Annotated[
                    str,
                    annotated_types.MaxLen(254,),
                ],],
            None,
        ] = None
    
    subject: typing.Annotated[
            str,
            annotated_types.MaxLen(250,),
        ]
    
    message: str
    
    sent_at: typing.Union[
            datetime.datetime,
            None,
        ]
    
    failed_at: typing.Union[
            datetime.datetime,
            None,
        ]
    
    received_at: typing.Union[
            datetime.datetime,
            None,
        ]
    
    created_at: datetime.datetime
