# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import datetime
import decimal
import gsmtasks.components.schemas.NestedAddress.schema
import types
import uuid


class AccountRole(lapidary.runtime.ModelBase):
    
    id: uuid.UUID
    
    url: str
    
    account: str
    
    user: typing.Union[
            str,
            None,
        ] = None
    
    state: str
    
    email: str
    
    display_name: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(100,),
            ],
            None,
        ] = None
    
    phone: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(128,),
            ],
            None,
        ] = None
    
    vehicle_registration_number: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(32,),
            ],
            None,
        ] = None
    
    vehicle_profile: typing.Union[
            str,
            None,
        ] = None
    
    vehicle_capacity: typing.Union[
            list[typing.Annotated[
                    int,
                    annotated_types.Le(2147483647,),
                    annotated_types.Ge(-2147483648,),
                ],],
            None,
        ] = None
    
    vehicle_speed_factor: typing.Union[
            decimal.Decimal,
            None,
        ] = None
    
    vehicle_service_time_factor: typing.Union[
            decimal.Decimal,
            None,
        ] = None
    
    optimize_return_to_depot: typing.Union[
            bool,
            None,
        ] = None
    
    optimize_earliest_start: typing.Union[
            datetime.time,
            None,
        ] = None
    
    optimize_latest_end: typing.Union[
            datetime.time,
            None,
        ] = None
    
    route_start_address: typing.Union[
            gsmtasks.components.schemas.NestedAddress.schema.NestedAddress,
            None,
        ] = None
    
    route_end_address: typing.Union[
            gsmtasks.components.schemas.NestedAddress.schema.NestedAddress,
            None,
        ] = None
    
    signature_image: typing.Union[
            str,
            None,
        ]
    
    is_admin: typing.Union[
            bool,
            None,
        ] = None
    
    is_manager: typing.Union[
            bool,
            None,
        ] = None
    
    is_worker: typing.Union[
            bool,
            None,
        ] = None
    
    is_integration: typing.Union[
            bool,
            None,
        ] = None
    
    is_active: bool
    
    is_on_duty: bool
    
    show_unassigned: typing.Union[
            bool,
            None,
        ] = None
    
    last_time_location: typing.Union[
            str,
            None,
        ]
    
    activated_at: typing.Union[
            datetime.datetime,
            None,
        ]
    
    deleted_at: typing.Union[
            datetime.datetime,
            None,
        ]
    
    created_at: datetime.datetime
    
    updated_at: datetime.datetime
