# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import datetime
import gsmtasks.components.schemas.NestedAddress.schema
import gsmtasks.components.schemas.NestedContact.schema
import types
import uuid


class PatchedContactAddress(lapidary.runtime.ModelBase):
    
    id: typing.Union[
            None,
            uuid.UUID,
        ] = None
    
    url: typing.Union[
            str,
            None,
        ] = None
    
    external_id: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(100,),
            ],
            None,
        ] = None
    
    account: typing.Union[
            str,
            None,
        ] = None
    
    client: typing.Union[
            str,
            None,
        ] = None
    
    contact: typing.Union[
            gsmtasks.components.schemas.NestedContact.schema.NestedContact,
            None,
        ] = None
    
    address: typing.Union[
            gsmtasks.components.schemas.NestedAddress.schema.NestedAddress,
            None,
        ] = None
    
    is_orderer: typing.Union[
            bool,
            None,
        ] = None
    
    is_receiver: typing.Union[
            bool,
            None,
        ] = None
    
    source: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(100,),
            ],
            None,
        ] = None
    
    created_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    updated_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
