# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import gsmtasks.components.schemas.Location.schema
import types


class TaskAssign(lapidary.runtime.ModelBase):
    
    notes: typing.Union[
            str,
            None,
        ] = None
    
    location: typing.Union[
            gsmtasks.components.schemas.Location.schema.Location,
            None,
        ] = None
    
    assignee: str
