# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import types


class AccountStripePaymentMethodAttach(lapidary.runtime.ModelBase):
    
    stripe_customer_id: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(255,),
            ],
            None,
        ] = None
    
    stripe_payment_method_id: typing.Annotated[
            str,
            annotated_types.MaxLen(255,),
        ]
    
    set_default: typing.Union[
            bool,
            None,
        ] = None
