# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import datetime
import gsmtasks.components.schemas.NestedAddress.schema
import gsmtasks.components.schemas.NestedContactAddress.schema
import types


class TaskCommandTaskData(lapidary.runtime.ModelBase):
    
    scheduled_time: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    position: typing.Union[
            typing.Annotated[
                float,
                annotated_types.Le(253402300799.0,),
                annotated_types.Ge(0.0,),
            ],
            None,
        ] = None
    
    metafields: typing.Union[
            dict[
                str,
                pydantic.JsonValue,
            ],
            None,
        ] = None
    
    address: typing.Union[
            gsmtasks.components.schemas.NestedAddress.schema.NestedAddress,
            None,
        ] = None
    
    contact_address: typing.Union[
            gsmtasks.components.schemas.NestedContactAddress.schema.NestedContactAddress,
            None,
        ] = None
    
    route: typing.Union[
            str,
            None,
        ] = None
    
    duration: typing.Union[
            dict[
                str,
                pydantic.JsonValue,
            ],
            None,
        ] = None
