# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import datetime
import gsmtasks.components.schemas.NestedContact.schema
import gsmtasks.components.schemas.TaskSerializerV2.schema
import types
import uuid


class OrderSerializerV2(lapidary.runtime.ModelBase):
    
    id: typing.Union[
            None,
            uuid.UUID,
        ] = None
    
    url: str
    
    account: str
    
    external_id: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(100,),
            ],
            None,
        ] = None
    
    reference: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(100,),
            ],
            None,
        ] = None
    
    client: typing.Union[
            str,
            None,
        ] = None
    
    orderer: typing.Union[
            gsmtasks.components.schemas.NestedContact.schema.NestedContact,
            None,
        ] = None
    
    tasks: typing.Union[
            list[str,],
            None,
        ] = None
    
    tasks_data: typing.Union[
            list[gsmtasks.components.schemas.TaskSerializerV2.schema.TaskSerializerV2,],
            None,
        ] = None
    
    documents: list[str,]
    
    auto_assign: typing.Union[
            bool,
            None,
        ] = None
    
    description: typing.Union[
            str,
            None,
        ] = None
    
    created_by: str
    
    recurrence: str
    
    created_at: datetime.datetime
    
    updated_at: datetime.datetime
