# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import datetime
import types
import uuid


class PatchedWebhook(lapidary.runtime.ModelBase):
    
    id: typing.Union[
            None,
            uuid.UUID,
        ] = None
    
    url: typing.Union[
            str,
            None,
        ] = None
    
    account: typing.Union[
            str,
            None,
        ] = None
    
    name: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(100,),
            ],
            None,
        ] = None
    
    version: typing.Union[
            str,
            None,
        ] = None
    
    state: typing.Union[
            str,
            None,
        ] = None
    
    headers: typing.Union[
            dict[
                str,
                pydantic.JsonValue,
            ],
            None,
        ] = None
    
    target: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(2048,),
            ],
            None,
        ] = None
    
    task_events: typing.Union[
            bool,
            None,
        ] = None
    
    document_events: typing.Union[
            bool,
            None,
        ] = None
    
    signature_events: typing.Union[
            bool,
            None,
        ] = None
    
    review_events: typing.Union[
            bool,
            None,
        ] = None
    
    notification_emails: typing.Union[
            list[typing.Annotated[
                    str,
                    annotated_types.MaxLen(254,),
                ],],
            None,
        ] = None
    
    fail_message: typing.Union[
            str,
            None,
        ] = None
    
    shared_secret: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(40,),
            ],
            None,
        ] = None
    
    activated_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    failed_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    created_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    updated_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
