# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types


class AccountStripePaymentMethodDetach(lapidary.runtime.ModelBase):
    
    stripe_payment_method_id: typing.Annotated[
            str,
            annotated_types.MaxLen(255,),
        ]
