# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import datetime
import gsmtasks.components.schemas.Location.schema
import gsmtasks.components.schemas.TaskCommandTaskData.schema
import types
import uuid


class TaskCommand(lapidary.runtime.ModelBase):
    
    id: uuid.UUID
    
    url: str
    
    account: str
    
    task: str
    
    external_id: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(100,),
            ],
            None,
        ] = None
    
    time: datetime.datetime
    
    action: str
    
    user: str
    
    notes: typing.Union[
            str,
            None,
        ] = None
    
    location: typing.Union[
            gsmtasks.components.schemas.Location.schema.Location,
            None,
        ] = None
    
    assignee: typing.Union[
            str,
            None,
        ] = None
    
    state: typing.Union[
            str,
            None,
        ] = None
    
    error_message: typing.Union[
            str,
            None,
        ] = None
    
    task_data: typing.Union[
            gsmtasks.components.schemas.TaskCommandTaskData.schema.TaskCommandTaskData,
            None,
        ] = None
    
    accepted_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    rejected_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    created_at: datetime.datetime
    
    updated_at: datetime.datetime
    
    model_config = pydantic.ConfigDict(extra='forbid',)
