# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import types
import uuid


class IntegrationRequest(lapidary.runtime.ModelBase):
    
    id: uuid.UUID
    
    account: str
    
    name: typing.Annotated[
            str,
            annotated_types.MaxLen(200,),
        ]
    
    notes: typing.Union[
            str,
            None,
        ] = None
    
    user: str
