# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing


class defaults(lapidary.runtime.ModelBase):
    
    transit_active_limit: int
    
    task_category: str
    
    create_contact_address: bool
    
    task_duration: dict[
            str,
            pydantic.JsonValue,
        ]
    
    distance_units: str
