# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import datetime
import types
import uuid


class Review(lapidary.runtime.ModelBase):
    
    id: uuid.UUID
    
    account: str
    
    tracker: str
    
    rating: typing.Annotated[
            int,
            annotated_types.Le(5,),
            annotated_types.Ge(1,),
        ]
    
    comment: typing.Union[
            str,
            None,
        ] = None
    
    last_task: str
    
    last_assignee: str
    
    created_at: datetime.datetime
