# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import datetime
import types
import uuid


class Notification(lapidary.runtime.ModelBase):
    
    id: uuid.UUID
    
    url: str
    
    method: str
    
    task: str
    
    template: typing.Union[
            str,
            None,
        ] = None
    
    event: typing.Union[
            str,
            None,
        ] = None
    
    state: typing.Union[
            str,
            None,
        ] = None
    
    assignee_proximity: typing.Union[
            str,
            None,
        ] = None
    
    recipient: typing.Union[
            str,
            None,
        ] = None
    
    emails: typing.Union[
            list[str,],
            None,
        ] = None
    
    phones: typing.Union[
            list[typing.Annotated[
                    str,
                    annotated_types.MaxLen(128,),
                ],],
            None,
        ] = None
    
    message: typing.Union[
            str,
            None,
        ] = None
    
    add_tracking_link: typing.Union[
            bool,
            None,
        ] = None
    
    sms_count: int
    
    sent_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    via_app: bool
    
    via_email: bool
    
    via_sms: bool
    
    created_at: datetime.datetime
    
    updated_at: datetime.datetime
