# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import datetime
import gsmtasks.components.schemas.ImportMappingLine.schema
import uuid


class ImportMapping(lapidary.runtime.ModelBase):
    
    id: uuid.UUID
    
    url: str
    
    account: str
    
    field_names: list[str,]
    
    lines: list[gsmtasks.components.schemas.ImportMappingLine.schema.ImportMappingLine,]
    
    created_at: datetime.datetime
