# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import uuid


class Addon(lapidary.runtime.ModelBase):
    
    id: uuid.UUID
    
    name: typing.Annotated[
            str,
            annotated_types.MaxLen(100,),
        ]
    
    short_description: str
    
    description: str
    
    price: typing.Annotated[
            str,
            annotated_types.MaxLen(50,),
        ]
    
    unit: typing.Annotated[
            str,
            annotated_types.MaxLen(50,),
        ]
    
    icon: str
