# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import datetime
import decimal
import gsmtasks.components.schemas.Location.schema
import types
import uuid


class TimeLocation(lapidary.runtime.ModelBase):
    
    id: uuid.UUID
    
    url: str
    
    source: typing.Union[
            str,
            None,
        ]
    
    user: str
    
    time: datetime.datetime
    
    location: gsmtasks.components.schemas.Location.schema.Location
    
    is_moving: typing.Union[
            bool,
            None,
        ] = None
    
    event: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(20,),
            ],
            None,
        ] = None
    
    activity_type: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(20,),
            ],
            None,
        ] = None
    
    state: typing.Union[
            str,
            None,
        ] = None
    
    heading: typing.Union[
            typing.Annotated[
                int,
                annotated_types.Le(2147483647,),
                annotated_types.Ge(-2147483648,),
            ],
            None,
        ] = None
    
    speed: typing.Union[
            typing.Annotated[
                int,
                annotated_types.Le(2147483647,),
                annotated_types.Ge(-2147483648,),
            ],
            None,
        ] = None
    
    altitude: typing.Union[
            typing.Annotated[
                int,
                annotated_types.Le(2147483647,),
                annotated_types.Ge(-2147483648,),
            ],
            None,
        ] = None
    
    accuracy: typing.Union[
            typing.Annotated[
                int,
                annotated_types.Le(2147483647,),
                annotated_types.Ge(-2147483648,),
            ],
            None,
        ] = None
    
    battery_level: typing.Union[
            decimal.Decimal,
            None,
        ] = None
    
    created_at: datetime.datetime
    
    updated_at: datetime.datetime
