# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import datetime
import gsmtasks.components.schemas.OrderData.schema
import types
import uuid


class PatchedRecurrence(lapidary.runtime.ModelBase):
    
    id: typing.Union[
            None,
            uuid.UUID,
        ] = None
    
    url: typing.Union[
            str,
            None,
        ] = None
    
    account: typing.Union[
            str,
            None,
        ] = None
    
    external_id: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(100,),
            ],
            None,
        ] = None
    
    assignee: typing.Union[
            str,
            None,
        ] = None
    
    route: typing.Union[
            str,
            None,
        ] = None
    
    order_data: typing.Union[
            gsmtasks.components.schemas.OrderData.schema.OrderData,
            None,
        ] = None
    
    tasks_data: typing.Union[
            dict[
                str,
                pydantic.JsonValue,
            ],
            None,
        ] = None
    
    is_active: typing.Union[
            bool,
            None,
        ] = None
    
    rrule: typing.Union[
            str,
            None,
        ] = None
    
    reset_recurrence: typing.Union[
            bool,
            None,
        ] = None
    
    timezone: typing.Union[
            str,
            None,
        ] = None
    
    last_recurred_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    last_scheduled_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    next_scheduled_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    created_by: typing.Union[
            str,
            None,
        ] = None
    
    created_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    updated_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
