# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import datetime
import types
import uuid


class TasksBackgroundImport(lapidary.runtime.ModelBase):
    
    id: uuid.UUID
    
    url: str
    
    account: str
    
    mapping: typing.Union[
            str,
            None,
        ] = None
    
    created_by: str
    
    tasks_data: list[dict[
                str,
                pydantic.JsonValue,
            ],]
    
    state: str
    
    started_at: typing.Union[
            datetime.datetime,
            None,
        ]
    
    completed_at: typing.Union[
            datetime.datetime,
            None,
        ]
    
    failed_at: typing.Union[
            datetime.datetime,
            None,
        ]
    
    errors: typing.Union[
            dict[
                str,
                pydantic.JsonValue,
            ],
            None,
        ] = None
    
    celery_task_id: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(50,),
            ],
            None,
        ] = None
    
    tasks_created: list[str,]
    
    assignees: list[str,]
    
    created_at: datetime.datetime
    
    updated_at: datetime.datetime
