# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import datetime
import gsmtasks.components.schemas.NestedAddress.schema
import gsmtasks.components.schemas.NestedContact.schema
import types
import uuid


class Task(lapidary.runtime.ModelBase):
    
    id: typing.Union[
            None,
            uuid.UUID,
        ] = None
    
    url: str
    
    account: str
    
    order: typing.Union[
            str,
            None,
        ] = None
    
    route: typing.Union[
            str,
            None,
        ] = None
    
    order_reference: str
    
    external_id: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(100,),
            ],
            None,
        ] = None
    
    category: typing.Union[
            str,
            None,
        ] = None
    
    orderer: typing.Union[
            str,
            None,
        ] = None
    
    orderer_name: str
    
    receiver: typing.Union[
            str,
            None,
        ] = None
    
    contact: typing.Union[
            gsmtasks.components.schemas.NestedContact.schema.NestedContact,
            None,
        ] = None
    
    address: gsmtasks.components.schemas.NestedAddress.schema.NestedAddress
    
    description: typing.Union[
            str,
            None,
        ] = None
    
    reference: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(100,),
            ],
            None,
        ] = None
    
    complete_after: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    complete_before: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    scheduled_time: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    state: str
    
    completed_at: typing.Union[
            datetime.datetime,
            None,
        ]
    
    cancelled_at: typing.Union[
            datetime.datetime,
            None,
        ]
    
    assignee: typing.Union[
            str,
            None,
        ] = None
    
    auto_assign: typing.Union[
            bool,
            None,
        ] = None
    
    assignee_proximity: str
    
    position: typing.Union[
            typing.Annotated[
                float,
                annotated_types.Le(253402300799.0,),
                annotated_types.Ge(0.0,),
            ],
            None,
        ] = None
    
    priority: typing.Union[
            typing.Annotated[
                int,
                annotated_types.Le(2147483647,),
                annotated_types.Ge(-2147483648,),
            ],
            None,
        ] = None
    
    duration: typing.Union[
            dict[
                str,
                pydantic.JsonValue,
            ],
            None,
        ] = None
    
    size: typing.Union[
            list[typing.Annotated[
                    int,
                    annotated_types.Le(2147483647,),
                    annotated_types.Ge(-2147483648,),
                ],],
            None,
        ] = None
    
    is_full_load: typing.Union[
            bool,
            None,
        ] = None
    
    metafields: typing.Union[
            dict[
                str,
                pydantic.JsonValue,
            ],
            None,
        ] = None
    
    forms: dict[
            str,
            pydantic.JsonValue,
        ]
    
    created_by: str
    
    issues: list[str,]
    
    created_at: datetime.datetime
    
    updated_at: datetime.datetime
    
    events: str
    
    documents: str
    
    signatures: str
    
    actions: dict[
            str,
            pydantic.JsonValue,
        ]
    
    counts: dict[
            str,
            pydantic.JsonValue,
        ]
