# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import types


class RouteArchive(lapidary.runtime.ModelBase):
    
    task_action: typing.Union[
            str,
            None,
        ] = None
