# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import gsmtasks.components.schemas.TimeLocation.schema
import types
import uuid


class UserExport(lapidary.runtime.ModelBase):
    
    id: uuid.UUID
    
    first_name: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(30,),
            ],
            None,
        ] = None
    
    last_name: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(30,),
            ],
            None,
        ] = None
    
    display_name: str
    
    email: str
    
    phone: str
    
    last_time_location: gsmtasks.components.schemas.TimeLocation.schema.TimeLocation
