# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import datetime
import gsmtasks.components.schemas.NestedAddress.schema
import types
import uuid


class RouteOptimizationSerializerV2(lapidary.runtime.ModelBase):
    
    id: uuid.UUID
    
    url: str
    
    account: str
    
    assignees: list[str,]
    
    state: str
    
    objective: typing.Union[
            str,
            None,
        ] = None
    
    tasks: list[str,]
    
    start_time: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    start_address: typing.Union[
            gsmtasks.components.schemas.NestedAddress.schema.NestedAddress,
            None,
        ] = None
    
    end_time: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    end_address: typing.Union[
            gsmtasks.components.schemas.NestedAddress.schema.NestedAddress,
            None,
        ] = None
    
    unassign_not_optimal: typing.Union[
            bool,
            None,
        ] = None
    
    ignore_time_windows: typing.Union[
            bool,
            None,
        ] = None
    
    total_distance: typing.Union[
            int,
            None,
        ]
    
    total_duration: typing.Union[
            dict[
                str,
                pydantic.JsonValue,
            ],
            None,
        ]
    
    commit: typing.Union[
            bool,
            None,
        ] = None
    
    created_by: typing.Union[
            str,
            None,
        ] = None
    
    commited_at: typing.Union[
            datetime.datetime,
            None,
        ]
    
    scheduled_at: typing.Union[
            datetime.datetime,
            None,
        ]
    
    started_at: typing.Union[
            datetime.datetime,
            None,
        ]
    
    ready_at: typing.Union[
            datetime.datetime,
            None,
        ]
    
    completed_at: typing.Union[
            datetime.datetime,
            None,
        ]
    
    failed_at: typing.Union[
            datetime.datetime,
            None,
        ]
    
    created_at: datetime.datetime
    
    updated_at: datetime.datetime
    
    errors: str
