# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import datetime
import types
import uuid


class properties(lapidary.runtime.ModelBase):
    
    model: typing.Union[
            str,
            None,
        ] = None
    
    url: typing.Union[
            str,
            None,
        ] = None
    
    task: typing.Union[
            None,
            uuid.UUID,
        ] = None
    
    task_event: typing.Union[
            str,
            None,
        ] = None
    
    event: typing.Union[
            str,
            None,
        ] = None
    
    from_state: typing.Union[
            str,
            None,
        ] = None
    
    to_state: typing.Union[
            str,
            None,
        ] = None
    
    user: typing.Union[
            None,
            uuid.UUID,
        ] = None
    
    notes: typing.Union[
            str,
            None,
        ] = None
    
    assignee: typing.Union[
            None,
            uuid.UUID,
        ] = None
    
    created_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    updated_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
