# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import datetime
import decimal
import types
import uuid


class StripePayment(lapidary.runtime.ModelBase):
    
    id: uuid.UUID
    
    url: str
    
    billable_account: str
    
    invoice: typing.Union[
            str,
            None,
        ]
    
    state: typing.Union[
            str,
            None,
        ] = None
    
    stripe_id: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(36,),
            ],
            None,
        ] = None
    
    stripe_state: typing.Union[
            str,
            None,
        ] = None
    
    amount: decimal.Decimal
    
    currency: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(3,),
            ],
            None,
        ] = None
    
    timestamp: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    response: typing.Union[
            str,
            None,
        ] = None
    
    created_at: datetime.datetime
    
    updated_at: datetime.datetime
