# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import types


class TaskListReorderRequest(lapidary.runtime.ModelBase):
    
    account: str
    
    assignee: typing.Union[
            str,
            None,
        ]
    
    assign_tasks: list[str,]
    
    reorder_tasks: list[str,]
