# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import types


class NestedContact(lapidary.runtime.ModelBase):
    
    name: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(200,),
            ],
            None,
        ] = None
    
    company: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(200,),
            ],
            None,
        ] = None
    
    phones: typing.Union[
            list[typing.Annotated[
                    str,
                    annotated_types.MaxLen(100,),
                ],],
            None,
        ] = None
    
    emails: typing.Union[
            list[typing.Annotated[
                    str,
                    annotated_types.MaxLen(100,),
                ],],
            None,
        ] = None
    
    notes: typing.Union[
            str,
            None,
        ] = None
