# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import datetime
import types
import uuid


class S3FileUpload(lapidary.runtime.ModelBase):
    
    id: uuid.UUID
    
    url: str
    
    file: str
    
    file_name: typing.Annotated[
            str,
            annotated_types.MaxLen(100,),
        ]
    
    file_type: typing.Annotated[
            str,
            annotated_types.MaxLen(100,),
        ]
    
    s3_signature: typing.Union[
            dict[
                str,
                pydantic.JsonValue,
            ],
            None,
        ]
    
    created_by: str
    
    source: typing.Union[
            str,
            None,
        ] = None
    
    created_at: datetime.datetime
    
    updated_at: datetime.datetime
