# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import datetime
import gsmtasks.components.schemas.TrackerTasks.schema
import gsmtasks.components.schemas.UserExport.schema
import types
import uuid


class TrackerPublic(lapidary.runtime.ModelBase):
    
    id: uuid.UUID
    
    account: str
    
    state: str
    
    assignees: list[gsmtasks.components.schemas.UserExport.schema.UserExport,]
    
    queue_positions: list[int,]
    
    tasks: list[gsmtasks.components.schemas.TrackerTasks.schema.TrackerTasks,]
    
    active_from: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    active_until: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    queued_states: typing.Union[
            list[str,],
            None,
        ] = None
    
    active_states: typing.Union[
            list[str,],
            None,
        ] = None
    
    show_driver_info: typing.Union[
            bool,
            None,
        ] = None
    
    show_destination: typing.Union[
            bool,
            None,
        ] = None
    
    show_eta: typing.Union[
            bool,
            None,
        ] = None
    
    show_sms_action: typing.Union[
            bool,
            None,
        ] = None
    
    show_call_action: typing.Union[
            bool,
            None,
        ] = None
    
    show_predicted_delivery: typing.Union[
            bool,
            None,
        ] = None
    
    show_last_task_event_notes: typing.Union[
            bool,
            None,
        ] = None
    
    show_last_task_images: typing.Union[
            bool,
            None,
        ] = None
    
    last_task_event_notes: str
    
    last_task_images: list[str,]
    
    logo: str
    
    show_logo: typing.Union[
            bool,
            None,
        ] = None
    
    show_path: typing.Union[
            bool,
            None,
        ] = None
    
    autozoom: typing.Union[
            bool,
            None,
        ] = None
    
    max_zoom_level: typing.Union[
            typing.Annotated[
                int,
                annotated_types.Le(2147483647,),
                annotated_types.Ge(-2147483648,),
            ],
            None,
        ] = None
    
    language: str
    
    reviews_allowed: typing.Union[
            bool,
            None,
        ] = None
    
    reviewed_at: typing.Union[
            datetime.datetime,
            None,
        ]
    
    predicted_delivery: typing.Union[
            datetime.datetime,
            None,
        ]
    
    predicted_delivery_calculated_at: typing.Union[
            datetime.datetime,
            None,
        ]
    
    predicted_delivery_error: typing.Union[
            str,
            None,
        ]
    
    default_map_location: dict[
            str,
            pydantic.JsonValue,
        ]
