# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import datetime
import types
import uuid


class ClientRole(lapidary.runtime.ModelBase):
    
    id: uuid.UUID
    
    url: str
    
    account: str
    
    client: str
    
    user: str
    
    phone: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(128,),
            ],
            None,
        ] = None
    
    is_manager: typing.Union[
            bool,
            None,
        ] = None
    
    is_active: typing.Union[
            bool,
            None,
        ] = None
    
    created_at: datetime.datetime
    
    updated_at: datetime.datetime
