# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import types
import uuid


class account(lapidary.runtime.ModelBase):
    
    name: typing.Annotated[
            str,
            annotated_types.MaxLen(100,),
        ]
    
    vatin: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(20,),
            ],
            None,
        ] = None
    
    billing_reference: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(20,),
            ],
            None,
        ] = None
    
    id: uuid.UUID
    
    registry_code: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(20,),
            ],
            None,
        ] = None
    
    slug: typing.Annotated[
            str,
            pydantic.Field(pattern=r'^[-a-zA-Z0-9_]+$',),
        ]
    
    billing_vat: typing.Union[
            bool,
            None,
        ] = None
    
    billing_email: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(254,),
            ],
            None,
        ] = None
