# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import types
import uuid


class FormRule(lapidary.runtime.ModelBase):
    
    id: uuid.UUID
    
    url: str
    
    account: str
    
    is_active: typing.Union[
            bool,
            None,
        ] = None
    
    name: typing.Annotated[
            str,
            annotated_types.MaxLen(50,),
        ]
    
    edit_url: typing.Annotated[
            str,
            annotated_types.MaxLen(2048,),
        ]
    
    view_url: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(2048,),
            ],
            None,
        ] = None
    
    pdf_url: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(2048,),
            ],
            None,
        ] = None
    
    rules: dict[
            str,
            pydantic.JsonValue,
        ]
    
    open_in: typing.Union[
            str,
            None,
        ] = None
