# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import datetime
import gsmtasks.components.schemas.NestedAddress.schema
import types
import uuid


class Route(lapidary.runtime.ModelBase):
    
    id: uuid.UUID
    
    url: str
    
    external_id: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(100,),
            ],
            None,
        ] = None
    
    account: str
    
    code: typing.Annotated[
            str,
            annotated_types.MaxLen(100,),
        ]
    
    name: typing.Annotated[
            str,
            annotated_types.MaxLen(100,),
        ]
    
    description: typing.Union[
            str,
            None,
        ] = None
    
    assignee: typing.Union[
            str,
            None,
        ] = None
    
    start_time: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    start_address: typing.Union[
            gsmtasks.components.schemas.NestedAddress.schema.NestedAddress,
            None,
        ] = None
    
    end_time: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    end_address: typing.Union[
            gsmtasks.components.schemas.NestedAddress.schema.NestedAddress,
            None,
        ] = None
    
    state: str
    
    objective: typing.Union[
            str,
            None,
        ] = None
    
    created_at: datetime.datetime
    
    updated_at: datetime.datetime
