# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import datetime
import types
import uuid


class ReadableUser(lapidary.runtime.ModelBase):
    
    id: uuid.UUID
    
    url: str
    
    first_name: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(30,),
            ],
            None,
        ] = None
    
    last_name: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(30,),
            ],
            None,
        ] = None
    
    display_name: str
    
    email: str
    
    phone: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(128,),
            ],
            None,
        ] = None
    
    intercom_hash: str
    
    signature_image: typing.Union[
            str,
            None,
        ] = None
    
    password_expires_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
