# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import datetime
import decimal
import gsmtasks.components.schemas.Invoice.properties.account.schema
import gsmtasks.components.schemas.InvoiceItem.schema
import types
import uuid


class Invoice(lapidary.runtime.ModelBase):
    
    id: uuid.UUID
    
    url: str
    
    account: gsmtasks.components.schemas.Invoice.properties.account.schema.account
    
    billing_method: str
    
    state: str
    
    period: typing.Union[
            list[datetime.date,],
            None,
        ]
    
    total_no_vat: typing.Union[
            decimal.Decimal,
            None,
        ]
    
    total_vat: decimal.Decimal
    
    total_with_vat: decimal.Decimal
    
    currency: str
    
    vat: bool
    
    due_date: typing.Union[
            datetime.date,
            None,
        ] = None
    
    paid_at: typing.Union[
            datetime.datetime,
            None,
        ]
    
    items: list[gsmtasks.components.schemas.InvoiceItem.schema.InvoiceItem,]
    
    pricing: uuid.UUID
    
    confirmed_by: str
    
    confirmed_at: typing.Union[
            datetime.datetime,
            None,
        ]
    
    created_at: datetime.datetime
    
    updated_at: datetime.datetime
