# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import datetime
import types
import uuid


class TaskForm(lapidary.runtime.ModelBase):
    
    id: uuid.UUID
    
    url: str
    
    task: str
    
    name: typing.Annotated[
            str,
            annotated_types.MaxLen(50,),
        ]
    
    link: str
    
    edit_url: typing.Annotated[
            str,
            annotated_types.MaxLen(2048,),
        ]
    
    view_url: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(2048,),
            ],
            None,
        ] = None
    
    pdf_url: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(2048,),
            ],
            None,
        ] = None
    
    open_in: str
    
    completed: typing.Union[
            bool,
            None,
        ] = None
    
    created_at: datetime.datetime
    
    updated_at: datetime.datetime
