# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import datetime
import decimal
import types


class properties(lapidary.runtime.ModelBase):
    
    model: typing.Union[
            str,
            None,
        ] = None
    
    source: typing.Union[
            str,
            None,
        ] = None
    
    user: typing.Union[
            str,
            None,
        ] = None
    
    time: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    state: typing.Union[
            str,
            None,
        ] = None
    
    heading: typing.Union[
            typing.Annotated[
                int,
                annotated_types.Le(2147483647,),
                annotated_types.Ge(-2147483648,),
            ],
            None,
        ] = None
    
    speed: typing.Union[
            typing.Annotated[
                int,
                annotated_types.Le(2147483647,),
                annotated_types.Ge(-2147483648,),
            ],
            None,
        ] = None
    
    altitude: typing.Union[
            typing.Annotated[
                int,
                annotated_types.Le(2147483647,),
                annotated_types.Ge(-2147483648,),
            ],
            None,
        ] = None
    
    accuracy: typing.Union[
            typing.Annotated[
                int,
                annotated_types.Le(2147483647,),
                annotated_types.Ge(-2147483648,),
            ],
            None,
        ] = None
    
    battery_level: typing.Union[
            decimal.Decimal,
            None,
        ] = None
    
    created_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    updated_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
