# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import datetime
import types
import uuid


class Client(lapidary.runtime.ModelBase):
    
    id: uuid.UUID
    
    url: str
    
    account: str
    
    name: typing.Annotated[
            str,
            annotated_types.MaxLen(200,),
        ]
    
    slug: typing.Annotated[
            str,
            pydantic.Field(pattern=r'^[-a-zA-Z0-9_]+$',),
        ]
    
    archived: typing.Union[
            bool,
            None,
        ] = None
    
    created_at: datetime.datetime
    
    updated_at: datetime.datetime
    
    contact_addresses: list[dict[
                str,
                pydantic.JsonValue,
            ],]
