# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import datetime
import gsmtasks.components.schemas.Location.schema
import uuid


class RouteOptimizationResultTask(lapidary.runtime.ModelBase):
    
    id: uuid.UUID
    
    task: str
    
    reference: str
    
    type: str
    
    state: str
    
    assignee: str
    
    address: str
    
    location: gsmtasks.components.schemas.Location.schema.Location
    
    arrival_time: datetime.datetime
    
    actual_arrival_time: datetime.datetime
    
    position: typing.Annotated[
            float,
            annotated_types.Le(253402300799.0,),
            annotated_types.Ge(0.0,),
        ]
    
    departure_time: datetime.datetime
    
    actual_departure_time: datetime.datetime
    
    distance: int
    
    actual_distance: int
