# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import datetime
import types
import uuid


class PushNotification(lapidary.runtime.ModelBase):
    
    id: uuid.UUID
    
    url: str
    
    account: str
    
    external_id: typing.Union[
            None,
            uuid.UUID,
        ] = None
    
    state: str
    
    notification: str
    
    recipient: str
    
    task: str
    
    event: typing.Union[
            str,
            None,
        ] = None
    
    subject: typing.Union[
            str,
            None,
        ] = None
    
    message: str
    
    error: typing.Union[
            str,
            None,
        ] = None
    
    pending_at: typing.Union[
            datetime.datetime,
            None,
        ]
    
    failed_at: typing.Union[
            datetime.datetime,
            None,
        ]
    
    sent_at: typing.Union[
            datetime.datetime,
            None,
        ]
    
    created_at: datetime.datetime
