# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import datetime
import gsmtasks.components.schemas.NestedAddress.schema
import gsmtasks.components.schemas.NestedContact.schema
import types
import uuid


class TrackerTasks(lapidary.runtime.ModelBase):
    
    id: uuid.UUID
    
    url: str
    
    state: typing.Union[
            str,
            None,
        ] = None
    
    category: typing.Union[
            str,
            None,
        ] = None
    
    assignee: typing.Union[
            None,
            uuid.UUID,
        ] = None
    
    contact: gsmtasks.components.schemas.NestedContact.schema.NestedContact
    
    address: gsmtasks.components.schemas.NestedAddress.schema.NestedAddress
    
    duration: typing.Union[
            dict[
                str,
                pydantic.JsonValue,
            ],
            None,
        ] = None
    
    scheduled_time: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    completed_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    cancelled_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    failed_at: datetime.datetime
