# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import datetime
import gsmtasks.components.schemas.NestedAddress.schema
import gsmtasks.components.schemas.NestedContact.schema
import types
import uuid


class ContactAddress(lapidary.runtime.ModelBase):
    
    id: uuid.UUID
    
    url: str
    
    external_id: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(100,),
            ],
            None,
        ] = None
    
    account: str
    
    client: typing.Union[
            str,
            None,
        ] = None
    
    contact: gsmtasks.components.schemas.NestedContact.schema.NestedContact
    
    address: gsmtasks.components.schemas.NestedAddress.schema.NestedAddress
    
    is_orderer: typing.Union[
            bool,
            None,
        ] = None
    
    is_receiver: typing.Union[
            bool,
            None,
        ] = None
    
    source: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(100,),
            ],
            None,
        ] = None
    
    created_at: datetime.datetime
    
    updated_at: datetime.datetime
