# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import gsmtasks.components.schemas.ConfigurationNotification.schema
import gsmtasks.components.schemas.ConfigurationSerializerV2.properties.account.schema
import gsmtasks.components.schemas.ConfigurationSerializerV2.properties.defaults.schema
import gsmtasks.components.schemas.ConfigurationSerializerV2.properties.settings.schema
import gsmtasks.components.schemas.ConfigurationSerializerV2.properties.user.schema
import types


class ConfigurationSerializerV2(lapidary.runtime.ModelBase):
    
    id: str
    
    account: gsmtasks.components.schemas.ConfigurationSerializerV2.properties.account.schema.account
    
    user: gsmtasks.components.schemas.ConfigurationSerializerV2.properties.user.schema.user
    
    is_staff: typing.Union[
            bool,
            None,
        ] = None
    
    app: str
    
    version: str
    
    auth: dict[
            str,
            pydantic.JsonValue,
        ]
    
    settings: gsmtasks.components.schemas.ConfigurationSerializerV2.properties.settings.schema.settings
    
    defaults: gsmtasks.components.schemas.ConfigurationSerializerV2.properties.defaults.schema.defaults
    
    features: dict[
            str,
            pydantic.JsonValue,
        ]
    
    templates: dict[
            str,
            pydantic.JsonValue,
        ]
    
    tracking: dict[
            str,
            pydantic.JsonValue,
        ]
    
    notifications: list[gsmtasks.components.schemas.ConfigurationNotification.schema.ConfigurationNotification,]
    
    permissions: dict[
            str,
            pydantic.JsonValue,
        ]
    
    legacy_views: dict[
            str,
            pydantic.JsonValue,
        ]
    
    services: dict[
            str,
            pydantic.JsonValue,
        ]
    
    is_client_role: typing.Union[
            bool,
            None,
        ] = None
    
    billing: dict[
            str,
            pydantic.JsonValue,
        ]
