# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import datetime
import types
import uuid


class SMS(lapidary.runtime.ModelBase):
    
    id: uuid.UUID
    
    url: str
    
    account: str
    
    external_id: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(34,),
            ],
            None,
        ] = None
    
    state: str
    
    notification: str
    
    sender: str
    
    alphanumeric_sender_id: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(20,),
            ],
            None,
        ] = None
    
    phone: typing.Annotated[
            str,
            annotated_types.MaxLen(128,),
        ]
    
    message: typing.Union[
            str,
            None,
        ] = None
    
    segments_count: typing.Union[
            typing.Annotated[
                int,
                annotated_types.Le(2147483647,),
                annotated_types.Ge(-2147483648,),
            ],
            None,
        ] = None
    
    error: typing.Union[
            str,
            None,
        ] = None
    
    sent_at: typing.Union[
            datetime.datetime,
            None,
        ]
    
    failed_at: typing.Union[
            datetime.datetime,
            None,
        ]
    
    received_at: typing.Union[
            datetime.datetime,
            None,
        ]
    
    created_at: datetime.datetime
