# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import types


class ImportMappingLine(lapidary.runtime.ModelBase):
    
    from_field: typing.Annotated[
            str,
            annotated_types.MaxLen(100,),
        ]
    
    to_field: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(100,),
            ],
            None,
        ] = None
    
    format: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(200,),
            ],
            None,
        ] = None
