# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import datetime
import types
import uuid


class PatchedExport(lapidary.runtime.ModelBase):
    
    id: typing.Union[
            None,
            uuid.UUID,
        ] = None
    
    url: typing.Union[
            str,
            None,
        ] = None
    
    account: typing.Union[
            str,
            None,
        ] = None
    
    export_model: typing.Union[
            str,
            None,
        ] = None
    
    field_names: typing.Union[
            list[typing.Annotated[
                    str,
                    annotated_types.MaxLen(100,),
                ],],
            None,
        ] = None
    
    format: typing.Union[
            str,
            None,
        ] = None
    
    link: typing.Union[
            str,
            None,
        ] = None
    
    created_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    updated_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
