# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import types
import uuid


class RegistrationUser(lapidary.runtime.ModelBase):
    
    id: uuid.UUID
    
    url: str
    
    name: typing.Annotated[
            str,
            annotated_types.MaxLen(30,),
        ]
    
    email: typing.Annotated[
            str,
            annotated_types.MaxLen(254,),
        ]
    
    phone: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(128,),
            ],
            None,
        ] = None
    
    password: typing.Annotated[
            str,
            annotated_types.MaxLen(100,),
            annotated_types.MinLen(6,),
        ]
