# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import datetime
import types
import uuid


class TaskMetadata(lapidary.runtime.ModelBase):
    
    id: uuid.UUID
    
    url: str
    
    task: str
    
    events_count: typing.Union[
            typing.Annotated[
                int,
                annotated_types.Le(32767,),
                annotated_types.Ge(0,),
            ],
            None,
        ] = None
    
    task_event_notes_count: typing.Union[
            typing.Annotated[
                int,
                annotated_types.Le(32767,),
                annotated_types.Ge(0,),
            ],
            None,
        ] = None
    
    documents_count: typing.Union[
            typing.Annotated[
                int,
                annotated_types.Le(32767,),
                annotated_types.Ge(0,),
            ],
            None,
        ] = None
    
    signatures_count: typing.Union[
            typing.Annotated[
                int,
                annotated_types.Le(32767,),
                annotated_types.Ge(0,),
            ],
            None,
        ] = None
    
    forms_count: typing.Union[
            typing.Annotated[
                int,
                annotated_types.Le(32767,),
                annotated_types.Ge(0,),
            ],
            None,
        ] = None
    
    forms_completed_count: typing.Union[
            typing.Annotated[
                int,
                annotated_types.Le(32767,),
                annotated_types.Ge(0,),
            ],
            None,
        ] = None
    
    last_task_event_notes: typing.Union[
            str,
            None,
        ] = None
    
    unassigned_duration: typing.Union[
            dict[
                str,
                pydantic.JsonValue,
            ],
            None,
        ] = None
    
    assigned_duration: typing.Union[
            dict[
                str,
                pydantic.JsonValue,
            ],
            None,
        ] = None
    
    accepted_duration: typing.Union[
            dict[
                str,
                pydantic.JsonValue,
            ],
            None,
        ] = None
    
    transit_duration: typing.Union[
            dict[
                str,
                pydantic.JsonValue,
            ],
            None,
        ] = None
    
    active_duration: typing.Union[
            dict[
                str,
                pydantic.JsonValue,
            ],
            None,
        ] = None
    
    completed_duration: typing.Union[
            dict[
                str,
                pydantic.JsonValue,
            ],
            None,
        ] = None
    
    failed_duration: typing.Union[
            dict[
                str,
                pydantic.JsonValue,
            ],
            None,
        ] = None
    
    cancelled_duration: typing.Union[
            dict[
                str,
                pydantic.JsonValue,
            ],
            None,
        ] = None
    
    unassigned_distance: typing.Union[
            typing.Annotated[
                int,
                annotated_types.Le(2147483647,),
                annotated_types.Ge(0,),
            ],
            None,
        ] = None
    
    assigned_distance: typing.Union[
            typing.Annotated[
                int,
                annotated_types.Le(2147483647,),
                annotated_types.Ge(0,),
            ],
            None,
        ] = None
    
    accepted_distance: typing.Union[
            typing.Annotated[
                int,
                annotated_types.Le(2147483647,),
                annotated_types.Ge(0,),
            ],
            None,
        ] = None
    
    transit_distance: typing.Union[
            typing.Annotated[
                int,
                annotated_types.Le(2147483647,),
                annotated_types.Ge(0,),
            ],
            None,
        ] = None
    
    active_distance: typing.Union[
            typing.Annotated[
                int,
                annotated_types.Le(2147483647,),
                annotated_types.Ge(0,),
            ],
            None,
        ] = None
    
    completed_distance: typing.Union[
            typing.Annotated[
                int,
                annotated_types.Le(2147483647,),
                annotated_types.Ge(0,),
            ],
            None,
        ] = None
    
    failed_distance: typing.Union[
            typing.Annotated[
                int,
                annotated_types.Le(2147483647,),
                annotated_types.Ge(0,),
            ],
            None,
        ] = None
    
    cancelled_distance: typing.Union[
            typing.Annotated[
                int,
                annotated_types.Le(2147483647,),
                annotated_types.Ge(0,),
            ],
            None,
        ] = None
    
    last_unassigned_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    last_assigned_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    last_accepted_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    last_transit_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    last_active_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    last_completed_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    last_failed_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    last_cancelled_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
