# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import types
import uuid


class RegistrationAccount(lapidary.runtime.ModelBase):
    
    id: uuid.UUID
    
    url: str
    
    name: typing.Annotated[
            str,
            annotated_types.MaxLen(100,),
        ]
    
    type: typing.Union[
            str,
            None,
        ] = None
    
    language: typing.Union[
            str,
            None,
        ] = None
    
    timezone: typing.Union[
            str,
            None,
        ] = None
    
    country_code: typing.Union[
            str,
            None,
        ] = None
    
    website: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(200,),
            ],
            None,
        ] = None
