# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import datetime
import decimal
import types
import uuid


class InvoiceItem(lapidary.runtime.ModelBase):
    
    id: uuid.UUID
    
    invoice: str
    
    name: typing.Annotated[
            str,
            annotated_types.MaxLen(200,),
        ]
    
    unit_price: decimal.Decimal
    
    quantity: decimal.Decimal
    
    unit: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(50,),
            ],
            None,
        ] = None
    
    total: decimal.Decimal
    
    created_at: datetime.datetime
    
    updated_at: datetime.datetime
