# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import datetime
import types
import uuid


class PatchedPushNotification(lapidary.runtime.ModelBase):
    
    id: typing.Union[
            None,
            uuid.UUID,
        ] = None
    
    url: typing.Union[
            str,
            None,
        ] = None
    
    account: typing.Union[
            str,
            None,
        ] = None
    
    external_id: typing.Union[
            None,
            uuid.UUID,
        ] = None
    
    state: typing.Union[
            str,
            None,
        ] = None
    
    notification: typing.Union[
            str,
            None,
        ] = None
    
    recipient: typing.Union[
            str,
            None,
        ] = None
    
    task: typing.Union[
            str,
            None,
        ] = None
    
    event: typing.Union[
            str,
            None,
        ] = None
    
    subject: typing.Union[
            str,
            None,
        ] = None
    
    message: typing.Union[
            str,
            None,
        ] = None
    
    error: typing.Union[
            str,
            None,
        ] = None
    
    pending_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    failed_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    sent_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    created_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
