# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import datetime
import gsmtasks.components.schemas.Location.schema
import types
import uuid


class TaskEvent(lapidary.runtime.ModelBase):
    
    id: uuid.UUID
    
    url: str
    
    account: str
    
    task: str
    
    task_command: str
    
    field: str
    
    event: str
    
    from_state: str
    
    to_state: str
    
    user: str
    
    notes: typing.Union[
            str,
            None,
        ] = None
    
    location: typing.Union[
            gsmtasks.components.schemas.Location.schema.Location,
            None,
        ] = None
    
    assignee: str
    
    created_at: datetime.datetime
    
    updated_at: datetime.datetime
