# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import types
import uuid


class TaskListReorderResponseTask(lapidary.runtime.ModelBase):
    
    id: uuid.UUID
    
    url: str
    
    state: typing.Union[
            str,
            None,
        ] = None
    
    position: typing.Union[
            typing.Annotated[
                float,
                annotated_types.Le(253402300799.0,),
                annotated_types.Ge(0.0,),
            ],
            None,
        ] = None
    
    assignee: str
