# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import datetime
import gsmtasks.components.schemas.OrderData.schema
import types
import uuid


class Recurrence(lapidary.runtime.ModelBase):
    
    id: uuid.UUID
    
    url: str
    
    account: str
    
    external_id: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(100,),
            ],
            None,
        ] = None
    
    assignee: typing.Union[
            str,
            None,
        ] = None
    
    route: typing.Union[
            str,
            None,
        ] = None
    
    order_data: typing.Union[
            gsmtasks.components.schemas.OrderData.schema.OrderData,
            None,
        ] = None
    
    tasks_data: typing.Union[
            dict[
                str,
                pydantic.JsonValue,
            ],
            None,
        ] = None
    
    is_active: typing.Union[
            bool,
            None,
        ] = None
    
    rrule: str
    
    reset_recurrence: typing.Union[
            bool,
            None,
        ] = None
    
    timezone: typing.Union[
            str,
            None,
        ] = None
    
    last_recurred_at: typing.Union[
            datetime.datetime,
            None,
        ]
    
    last_scheduled_at: typing.Union[
            datetime.datetime,
            None,
        ]
    
    next_scheduled_at: typing.Union[
            datetime.datetime,
            None,
        ]
    
    created_by: str
    
    created_at: datetime.datetime
    
    updated_at: datetime.datetime
