# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import datetime
import types
import uuid


class PatchedBraintreeCustomer(lapidary.runtime.ModelBase):
    
    id: typing.Union[
            None,
            uuid.UUID,
        ] = None
    
    url: typing.Union[
            str,
            None,
        ] = None
    
    braintree_id: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(36,),
            ],
            None,
        ] = None
    
    account: typing.Union[
            str,
            None,
        ] = None
    
    first_name: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(255,),
            ],
            None,
        ] = None
    
    last_name: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(255,),
            ],
            None,
        ] = None
    
    company: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(255,),
            ],
            None,
        ] = None
    
    email: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(254,),
            ],
            None,
        ] = None
    
    phone: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(14,),
            ],
            None,
        ] = None
    
    website: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(100,),
            ],
            None,
        ] = None
    
    vat: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(20,),
            ],
            None,
        ] = None
    
    payment_method_nonce: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(250,),
            ],
            None,
        ] = None
    
    created_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    updated_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
