# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import gsmtasks.components.schemas.Document.schema
import gsmtasks.components.schemas.TaskMetadata.schema
import gsmtasks.components.schemas.TaskSerializerV2.schema
import types


class TaskListExt(lapidary.runtime.ModelBase):
    
    tasks: list[gsmtasks.components.schemas.TaskSerializerV2.schema.TaskSerializerV2,]
    
    documents: typing.Union[
            list[gsmtasks.components.schemas.Document.schema.Document,],
            None,
        ] = None
    
    metadatas: typing.Union[
            list[gsmtasks.components.schemas.TaskMetadata.schema.TaskMetadata,],
            None,
        ] = None
