# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import types


class OrderData(lapidary.runtime.ModelBase):
    
    auto_assign: typing.Union[
            bool,
            None,
        ] = None
    
    description: typing.Union[
            str,
            None,
        ] = None
    
    reference: typing.Union[
            typing.Annotated[
                str,
                annotated_types.MaxLen(100,),
            ],
            None,
        ] = None
    
    client: typing.Union[
            str,
            None,
        ] = None
    
    orderer: typing.Union[
            dict[
                str,
                pydantic.JsonValue,
            ],
            None,
        ] = None
