# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import datetime
import types


class InvoicePayment(lapidary.runtime.ModelBase):
    
    paid_at: typing.Union[
            datetime.datetime,
            None,
        ] = None
