# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import datetime
import types
import uuid


class ContactAddressBackgroundImport(lapidary.runtime.ModelBase):
    
    id: uuid.UUID
    
    url: str
    
    account: str
    
    created_by: str
    
    contact_addresses_data: list[dict[
                str,
                pydantic.JsonValue,
            ],]
    
    state: str
    
    started_at: typing.Union[
            datetime.datetime,
            None,
        ]
    
    completed_at: typing.Union[
            datetime.datetime,
            None,
        ]
    
    failed_at: typing.Union[
            datetime.datetime,
            None,
        ]
    
    errors: dict[
            str,
            pydantic.JsonValue,
        ]
    
    celery_task_id: typing.Union[
            str,
            None,
        ]
    
    contact_addresses_created: list[str,]
    
    created_at: datetime.datetime
    
    updated_at: datetime.datetime
