# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import annotated_types
import datetime
import types
import uuid


class Export(lapidary.runtime.ModelBase):
    
    id: uuid.UUID
    
    url: str
    
    account: str
    
    export_model: str
    
    field_names: typing.Union[
            list[typing.Annotated[
                    str,
                    annotated_types.MaxLen(100,),
                ],],
            None,
        ] = None
    
    format: str
    
    link: str
    
    created_at: datetime.datetime
    
    updated_at: datetime.datetime
